version: "3"

services:
  #
  # Node
  #
  node:
    image: node:12-alpine
    volumes:
      - ./frontend:/usr/src/enjoyingredients
    working_dir: /usr/src/enjoyingredients
    restart: "no"
    command: npm install
