backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  # Single pages
  - name: "pages"
    label: "Individuelle Seiten"
    files:
      - name: "about"
        label: "Über mich"
        file: "content/about.md"
        fields:
          - name: "title"
            label: "Titel"
            widget: string
          - name: "avatar"
            label: "Avatar"
            widget: "image"
          - name: "body"
            label: "Inhalt"
            widget: "markdown"

  # Blog Posts
  - name: "blog_posts"
    label: "Blog Posts"
    label_singular: "Blog Post"
    editor:
      preview: true
    folder: "content/blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Titel"
        widget: "string"
      - name: "thumbnail"
        label: "Thumbnail"
        widget: "image"
        required: false
      - name: "date"
        label: "Veröffentlichungsdatum"
        widget: "date"
        format: "YYYY-MM-DD"
      - name: "categories"
        label: "Kategorien"
        widget: "relation"
        collection: "blog_categories"
        searchFields: ["name"]
        valueField: "name"
      - name: "description"
        label: "Kurzbeschreibung"
        widget: "text"
      - name: "body"
        label: "Inhalt"
        widget: "markdown"

  # Blog categories
  - name: "blog_categories"
    label: "Kategorien"
    label_singular: "Kategorie"
    editor:
      preview: false
    folder: "content/blog/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - name: "title"
        label: "Name"
        widget: "string"
      - name: "thumbnail"
        label: "Thumbnail"
        widget: "image"
        required: false
      - name: "description"
        label: "Kurzbeschreibung"
        widget: "text"
