backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "blog_posts"
    label: "Blog Posts"
    label_singular: "Blog Post"
    editor:
      preview: true
    folder: "content/blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Titel"
        name: "title"
        widget: "string"
      - label: "Status"
        name: "status"
        widget: "select"
        options:
          - { label: "Entwurf", value : 0 }
          - { label: "Im Review", value: 1 }
          - { label: "Veröffentlicht", value: 2 }
        default: "Entwurf"
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        required: false
      - label: "Veröffentlichungsdatum"
        name: "date"
        widget: "date"
        format: "DD.MM.YYYY"
      - label: "Kategorien"
        name: "categories"
        widget: "relation"
        collection: "blog_categories"
        searchFields: ["name"]
        valueField: "name"
      - label: "Kurzbeschreibung"
        name: "description"
        widget: "text"
      - label: "Inhalt"
        name: "body"
        widget: "markdown"
  - name: "blog_categories"
    label: "Kategorien"
    label_singular: "Kategorie"
    editor:
      preview: false
    folder: "content/blog/categories"
    create: true
    slug: "{{slug}}"
    identifier_field: "name"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        required: false
      - label: "Kurzbeschreibung"
        name: "description"
        widget: "text"
