backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "blog_posts"
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "content/blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Publish Date", name: "date", widget: "date", format: "DD.MM.YYYY" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
