backend:
  name: git-gateway
  branch: netlify_dev

# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1
#   branch: netlify_dev

# backend:
#   name: test-repo

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

locale: 'de'

slug:
  encoding: 'unicode'

collections:
  # Single pages
  - name: 'pages'
    label: 'Individuelle Seiten'
    # folder: 'content/pages'
    # path: '{{slug}}/index'
    # media_folder: ''
    # public_folder: ''
    files:
      - name: 'about'
        label: 'Über mich und die Welt'
        file: 'content/pages/about/index.md'
        fields:
          - name: 'title'
            label: 'Titel'
            widget: string
          - name: 'body'
            label: 'Inhalt'
            widget: 'markdown'

  # Blog Posts
  - name: 'blog_posts'
    label: 'Blog Posts'
    label_singular: 'Blog Post'
    create: true
    editor:
      preview: true
    folder: 'content/blog/posts'
    slug: '{{slug}}'
    path: '{{slug}}/index'
    media_folder: 'content/blog/posts/{{slug}}'
    # public_folder: ''
    fields:
      - name: 'title'
        label: 'Titel'
        widget: 'string'
      - name: 'thumbnail'
        label: 'Thumbnail'
        widget: 'image'
        required: false
      - name: 'date'
        label: 'Veröffentlichungsdatum'
        widget: 'date'
        format: 'YYYY-MM-DD'
      - name: 'categories'
        label: 'Kategorien'
        widget: 'relation'
        collection: 'blog_categories'
        searchFields: ['name']
        valueField: 'name'
        required: false
      - name: 'description'
        label: 'Kurzbeschreibung'
        widget: 'text'
      - name: 'body'
        label: 'Inhalt'
        widget: 'markdown'

  # Blog categories
  - name: 'blog_categories'
    label: 'Kategorien'
    label_singular: 'Kategorie'
    create: true
    editor:
      preview: false
    folder: 'content/blog/categories'
    slug: '{{slug}}'
    fields:
      - name: 'title'
        label: 'Name'
        widget: 'string'
      - name: 'thumbnail'
        label: 'Thumbnail'
        widget: 'image'
        required: false
      - name: 'description'
        label: 'Kurzbeschreibung'
        widget: 'text'
