version: '3.3'

networks:
  traefiknet:
  internal:

volumes:
  db_data:
  ghost_content:

services:
##############################
# Traefik Reverse Proxy
# https://hub.docker.com/_/traefik/
##############################
  traefik:
    image: traefik:2.2
    restart: unless-stopped
    command:
      # Webpanel
      - --api=true
      - --api.dashboard=true
      # HTTP
      - --entrypoints.web.address=:80 # web is a custom name
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443 # websecure is a custom name
      # Docker
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=traefiknet
      # TLS
      - --certificatesresolvers.lencrypt.acme.email=${ACME_EMAIL} # lencrypt is a custom name
      - --certificatesresolvers.lencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.lencrypt.acme.tlschallenge=true
      - --certificatesresolvers.lencrypt.acme.httpchallenge.entrypoint=web
      # - --certificatesresolvers.lencrypt.acme.caserver= https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.lencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    labels:
      # Webpanel
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${DOMAINS_TRAEFIK}`)" # api is a custom name
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=lencrypt"
      # Webpanel authentication
      - "traefik.http.routers.api.middlewares=user-auth"
      - "traefik.http.middlewares.user-auth.basicauth.users=${BASIC_AUTH}" # user-auth is a custom name
      # Security headers
      - "traefik.http.middlewares.securityHeader.headers.framedeny=true" # securityHeader is a custom name
      - "traefik.http.middlewares.securityHeader.headers.sslredirect=true"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
      - traefiknet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/letsencrypt:/letsencrypt

##############################
# Watchtower
# https://hub.docker.com/r/containrrr/watchtower
#
# Applies updates (if available) at midnight.
##############################
  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    command: --cleanup --schedule "0 0 0 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

##############################
# MariaDB
# https://hub.docker.com/_/mariadb/
##############################
  db:
    image: mariadb:10.5
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

##############################
# Ghost CMS
# https://hub.docker.com/_/ghost/
##############################
  ghost:
    image: ghost:3.29-alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`${DOMAINS_BLOG}`)"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls=true"
      - "traefik.http.routers.ghost.tls.certresolver=lencrypt"
    depends_on:
      - db
      - mail
      - traefik
    networks:
      - internal
      - traefiknet
    volumes:
      - type: volume
        source: ghost_content
        target: /var/lib/ghost/content
    environment:
      url: ${BLOG_URL}
      database__client: mysql
      database__connection__host: db
      database__connection__database: ${DB_NAME}
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      mail__transport: SMTP
      mail__from: "Ghost CMS <${SERVER_EMAIL}>"
      mail__options__service: SMTP
      mail__options__host: mail
      mail__options__port: 25

##############################
# Matomo
# https://hub.docker.com/_/matomo
##############################
  # matomo:
  #   image: matomo:3.14
  #   restart: unless-stopped
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.matomo.rule=Host(`${DOMAINS_MATOMO}`)"
  #     - "traefik.http.routers.matomo.entrypoints=websecure"
  #     - "traefik.http.routers.matomo.tls=true"
  #     - "traefik.http.routers.matomo.tls.certresolver=lencrypt"
  #   depends_on:
  #     - db
  #     - mail
  #   networks:
  #     - internal
  #     - traefiknet
  #   volumes:
  #     - ./config/matomo/matomo:/var/www/html/config:rw
  #     - ./confg/matomo/php.ini:/usr/local/etc/php/php.ini

##############################
# Mail service
# https://hub.docker.com/r/bytemark/smtp
#
# This allows Matomo and Ghost to send email straight out of the box.
# It makes an SMTP host available at the hostname "mail".
##############################
  mail:
    image: bytemark/smtp
    restart: unless-stopped
    networks:
      - traefiknet
